### ISSUE TITLE
Join the competition! https://lmsys.org/blog/2023-05-03-arena/

### ISSUE THREAD

**Issue by yhyu13** [BlinkDL/RWKV-LM#105]
LMSYS org was rolling out some serious back to back battle between LLMs, I would like you see RWKV's debut there 👍

**Comment by BlinkDL** [comment]
The prompt & sampling there are not optimized, so I am curious to see where it will land :)

**Comment by BlinkDL** [comment]
https://twitter.com/BlinkDL_AI/status/1656462292031246338
