### ISSUE TITLE
How to construct  dataset for multi-round dialogue? any examples?

### ISSUE THREAD

**Issue by hitxueliang** [BlinkDL/RWKV-LM#106]
Can anyone give some data examples for multi-round dialogue. 
MOSS and ChatGLM have clear examples, but I can not find examples in RWKV

**Comment by BlinkDL** [comment]
see https://github.com/BlinkDL/ChatRWKV and search for "When you build a RWKV chatbot"

**Comment by gg22mm** [comment]
多轮格式是这样吗？
数据 sample.jsonl：
 Bob: 你叫什么名字\n\nAlice: 我叫小王
 Bob: 1+1=？\n\nAlice: 等于二\n\nBob: 不是3吗？\n\nAlice:不是哦，是2
#
还有那怎么训练呢？从0开始训练可以吗？
cd /RWKV-LM/RWKV-v4 
用 python train.py 可以训练上面的样式吗?
