### ISSUE TITLE
A request for the RWKV model icon.

### ISSUE THREAD

**Issue by EliverQ** [BlinkDL/RWKV-LM#107]
Dear PENG Bo,

I hope this message finds you well. Sorry to disturb you through this issue because I can't find other contact information.

We are currently working on a survey about large language models [(https:/github.com/RUCAIBoXLLMSurvey)](https:/github.com/RUCAIBoXLLMSurvey). In order to cover as many existing models as possible, we are wondering if it would be possible to obtain the icon for your RWKV model to use in figure 1 of the survey.
Your contribution to the field has been invaluable and we believe that your work would greatly enrich our paper, ] would be happy to cite your work appropriately.

Thank you very much for considering my request. I look forward to hearing from you soon.

Best regards,
The survey team

**Comment by BlinkDL** [comment]
Can simply use https://pbs.twimg.com/profile_images/1570827382533263360/pm3SqAGC_400x400.jpg for now :)
