### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by djstrong** [BlinkDL/RWKV-LM#112]
Why do you claim this as Apache license? It is trained using e.g. Alpaca which is non commercial...
Could you write in the Readme a section about license (preferably with licenses of used data/models)?

**Comment by BlinkDL** [comment]
RWKV-4 is trained using 100% Pile

**Comment by djstrong** [comment]
I am referring to (on top of the readme):
>Raven 14B (finetuned on Alpaca+ShareGPT+...) Demo: https://huggingface.co/spaces/BlinkDL/ChatRWKV-gradio

>Raven 7B (finetuned on Alpaca+ShareGPT+...) Demo: https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B
