### ISSUE TITLE
Converting to huggingface

### ISSUE THREAD

**Issue by lambdaofgod** [BlinkDL/RWKV-LM#113]
sgugger [made huggingface class for RWKV](https://github.com/huggingface/transformers/pull/22797).

Do you know by any chance how he converted the model?

I've asked him how he did it, I think it'd be great to document here how RWKV can be used in transformers.
A script to convert to PyTorch like [this format](https://huggingface.co/sgugger/rwkv-7b-pile/tree/main) would make it straightforward to port your new models :)

**Comment by 3outeille** [comment]
@lambdaofgod https://huggingface.co/RWKV

**Comment by Galaxy-Ding** [comment]
> sgugger [made huggingface class for RWKV](https://github.com/huggingface/transformers/pull/22797).
> 
> Do you know by any chance how he converted the model?
> 
> I've asked him how he did it, I think it'd be great to document here how RWKV can be used in transformers. A script to convert to PyTorch like [this format](https://huggingface.co/sgugger/rwkv-7b-pile/tree/main) would make it straightforward to port your new models :)

Hi, I'm new to this huggingface transformation.
I now have:

- rwkv.pth
- convert_rwkv_checkpoint_to_hf.py

I want to convert it into a huggingface model like yours repo [https://huggingface.co/RWKV]

- config.json
- generation_config.json
- pytorch_model-00001-of-00017.bin
- pytorch_model-00002-of-00017.bin
- pytorch_model-00003-of-00017.bin
- pytorch_model-00004-of-00017.bin
- pytorch_model-00005-of-00017.bin
- pytorch_model-00006-of-00017.bin
- pytorch_model-00007-of-00017.bin
- pytorch_model-00008-of-00017.bin
- pytorch_model-00009-of-00017.bin
- pytorch_model-00010-of-00017.bin
- pytorch_model-00011-of-00017.bin
- pytorch_model-00012-of-00017.bin
- pytorch_model-00013-of-00017.bin
- pytorch_model-00014-of-00017.bin
- pytorch_model-00015-of-00017.bin
- pytorch_model-00016-of-00017.bin
- pytorch_model-00017-of-00017.bin
- pytorch_model.bin.index.json
- special_tokens_map.json
- tokenizer.json
- tokenizer_config.json]

What should I do to become a warehouse like yours? Can you be more detailed?

**Comment by Galaxy-Ding** [comment]
> @lambdaofgod https://huggingface.co/RWKV

Hi, I'm new to this huggingface transformation.
I now have:

- rwkv.pth
- convert_rwkv_checkpoint_to_hf.py

I want to convert it into a huggingface model like yours repo [https://huggingface.co/RWKV]

- config.json
- generation_config.json
- pytorch_model-00001-of-00017.bin
- pytorch_model-00002-of-00017.bin
- pytorch_model-00003-of-00017.bin
- pytorch_model-00004-of-00017.bin
- pytorch_model-00005-of-00017.bin
- pytorch_model-00006-of-00017.bin
- pytorch_model-00007-of-00017.bin
- pytorch_model-00008-of-00017.bin
- pytorch_model-00009-of-00017.bin
- pytorch_model-00010-of-00017.bin
- pytorch_model-00011-of-00017.bin
- pytorch_model-00012-of-00017.bin
- pytorch_model-00013-of-00017.bin
- pytorch_model-00014-of-00017.bin
- pytorch_model-00015-of-00017.bin
- pytorch_model-00016-of-00017.bin
- pytorch_model-00017-of-00017.bin
- pytorch_model.bin.index.json
- special_tokens_map.json
- tokenizer.json
- tokenizer_config.json]

What should I do to become a warehouse like yours? Can you be more detailed?
