### ISSUE TITLE
UTF-16 stream does not start with BOM

### ISSUE THREAD

**Issue by ItsCRC** [BlinkDL/RWKV-LM#119]
Hi all, 

I have trained RWKV-v4neo from scratch. After going through some issues, it seems that I need to execute run.py in RWKV-v4 to test my model. I changed the code as follows in run.py:
```

if TOKEN_MODE == 'char':
    MODEL_NAME = '/home/ubuntu/RWKV-v4neo/out/rwkv-450'
    WORD_NAME = '/home/ubuntu/RWKV-v4neo/out/vocab'

```
When executing `python run.py`, it gives `UnicodeError: UTF-16 stream does not start with BOM`

Any suggestions @BlinkDL ?

**Comment by BlinkDL** [comment]
hi resave vocab.json as UTF-8 and change util.py to load tokenizer as UTF-8
