### ISSUE TITLE
txt数据集格式

### ISSUE THREAD

**Issue by cy565025164** [BlinkDL/RWKV-LM#128]
“tokenize .txt into train.npy data”，.txt数据能给一些例子吗？

**Comment by Leoeeeeeeea** [comment]
i need too!!!

**Comment by BlinkDL** [comment]
@cy565025164 @Leoeeeeeeea 请阅读
https://zhuanlan.zhihu.com/p/638326262
https://zhuanlan.zhihu.com/p/639629050
