### ISSUE TITLE
Initializing single layer

### ISSUE THREAD

**Issue by DanielRoeder1** [BlinkDL/RWKV-LM#137]
Hello, 

I am planning to use a single Block of the RWKV architecture on top of another model. 
As I am fairly new to using Cuda kernels I am not sure how I would correctly initialize a single RWKV block alongside my model.

The idea is that the block receives a collection of tokens which it uses to build the internal state.

Thankful for any guidance.

**Comment by BlinkDL** [comment]
Hi you can ask in Discord https://discord.gg/bDSBUMeFpc
