### ISSUE TITLE
Lora微调灾难性遗忘

### ISSUE THREAD

**Issue by reckzhou** [BlinkDL/RWKV-LM#141]
完全采用垂直领域的样本，结果忘记通用领域的所有技能。
不确定在这个模型中如何解决这个问题？
----
Forget all the skills in the general domain with my samples.
How to fix this in this model?

**Comment by Triang-jyed-driung** [comment]
去这里https://github.com/Blealtan/RWKV-LM-LoRA/issues提问吧

**Comment by reckzhou** [comment]
感谢
