### ISSUE TITLE
python train.py failed in windows11 platform, during ninja build wkv.o

### ISSUE THREAD

**Issue by HackGiter** [BlinkDL/RWKV-LM#145]
![image](https://github.com/BlinkDL/RWKV-LM/assets/50295237/4e2a08da-a748-4270-a5c8-2db4802c5c6f)

1.CUDA\Pytorch\Pytorch-lightning version just match the requirements, but just not working. I'm wondering what kind of GPU do it support.
2.What version should ninja be?

**Comment by BlinkDL** [comment]
you can remove -maxxxxx 60 in windows
