### ISSUE TITLE
v4 model.py vs model_run.py

### ISSUE THREAD

**Issue by jingweiz** [BlinkDL/RWKV-LM#15]
Hi,
Thanks for this awesome repo!
I'm trying to understand the code and found that in the v4 folder, there's this model.py and model_run.py, which contains GPT and RWKV_GPT respectively which all uses different initialization methods. Could you elaborate on when should which one be used? Thanks in advnace!

**Comment by BlinkDL** [comment]
model.py is for training so it has the correct initialization

**Comment by jingweiz** [comment]
Great, thanks for the fast reply! Another question, if I want to test run this on a laptop that has no graphics card, how should I surpass the `wkv_cuda` function? Is there a cpu compatible version for that? Thank you so much!

**Comment by BlinkDL** [comment]
you can use CPU for inference.
see https://github.com/BlinkDL/RWKV-LM/blob/main/RWKV-v4neo/run.py
