### ISSUE TITLE
windows平台下vscode运行RWKV-V4 train.py 报错 RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by psile** [BlinkDL/RWKV-LM#158]
已经下载Ninja，但是还是报错，有解决办法吗，小白求救

**Comment by BlinkDL** [comment]
Install VS2022 build tools (https://aka.ms/vs/17/release/vs_BuildTools.exe select Desktop C++). Reinstall CUDA 11.7 (install VC++ extensions). Run v2/chat.py in "x64 native tools command prompt".
