### ISSUE TITLE
transformers代码加载cuda失败

### ISSUE THREAD

**Issue by wpwpwpyo** [BlinkDL/RWKV-LM#159]
您好，我下载了4.30.2版本的transformers，model = RwkvModel.from_pretrained("RWKV/rwkv-4-169m-pile")载入rwkv模型时，modeling_rwkv.py文件中的load_wkv_cuda_kernel函数不能正确执行，报错为：
![图片](https://github.com/BlinkDL/RWKV-LM/assets/49509792/d7388256-d34f-4abf-b500-09acb3285790)

我的nvcc -V是11.6版本：
![图片](https://github.com/BlinkDL/RWKV-LM/assets/49509792/b8b47ed6-81e0-4db4-ae6c-f43c7e4d2572)

并且根据pytorch官网安装了1.13.1的版本：conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia

请问缺失的cudart如何进行正确的安装？

**Comment by xiaol** [comment]
325154699 加技术研发群

**Comment by BlinkDL** [comment]
@wpwpwpyo @wywzxxz 
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
