### ISSUE TITLE
Cannot train a added module using RWKV_GPT in RWKV-4/src/model_run.py

### ISSUE THREAD

**Issue by StarDewXXX** [BlinkDL/RWKV-LM#162]
When I add a module to the network  RWKV_GPT in RWKV-4/src/model_run.py , the newly added module cannot join the back propagation(The parameter is not updated at all). Is it caused by the WKV(torch.autograd.Function) ? And how can I fix this?

**Comment by BlinkDL** [comment]
try v4neo
