### ISSUE TITLE
Loading extension module wkv_512...  Fail

### ISSUE THREAD

**Issue by anonymitynewbie** [BlinkDL/RWKV-LM#169]
I chaged the train.py to my model , and ran "model = RWKV(args)".
when "Loading extension module wkv_512...", 
ImportError: DLL load failed while importing wkv_512: 找不到指定的模块。
Need I download the file ? or where can i find it?

**Comment by BlinkDL** [comment]
use v4neo/train.py and run in ubuntu first

**Comment by anonymitynewbie** [comment]
i run it in Windows' Pycharm, i find that  it did not generate .pyd file causing "ImportError: DLL load failed while importing wkv: 找不到指定的模块。"  how can i solve this ?

**Comment by BlinkDL** [comment]
# How to build in Linux:
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

# How to build in win:
Install VS2022 build tools (https://aka.ms/vs/17/release/vs_BuildTools.exe select Desktop C++). Reinstall CUDA 11.7 (install VC++ extensions). Run train.py in "x64 native tools command prompt".
