### ISSUE TITLE
windows11 安装失败 The runtime failed to install correct y.Please try again.

### ISSUE THREAD

**Issue by PhilRandWu** [BlinkDL/RWKV-LM#191]
windows11下通过 exe 安装报错
![image](https://github.com/BlinkDL/RWKV-LM/assets/71576743/4cd319b9-9c4c-444a-8839-f24649302ca8)
The runtime failed to install correct y.Please try again.

**Comment by BlinkDL** [comment]
use RWKV-Runner https://github.com/josStorer/RWKV-Runner/releases
