### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by surviveMiao** [BlinkDL/RWKV-LM#195]
在运行chat.py文件时，报出如下错误：
![image](https://github.com/BlinkDL/RWKV-LM/assets/96619920/c62df6cc-0acd-476b-9eca-0f95873a4a60)
python 3.10 
cuda 12.1
torch 2.0

**Comment by BlinkDL** [comment]
pip install rwkv --upgrade

**Comment by BlinkDL** [comment]
fixed in rwkv pip package 0.8.20

**Comment by surviveMiao** [comment]
谢谢！
