### ISSUE TITLE
lora训练时出错

### ISSUE THREAD

**Issue by surviveMiao** [BlinkDL/RWKV-LM#196]
我运行RWKV-v4neo下的train.py文件，但是它启动不起来，自己断 还没反应
显示的界面
![QJ45B5LV2FFD J925`CSR2W](https://github.com/BlinkDL/RWKV-LM/assets/96619920/052d79ae-52d7-4b11-9c3b-96a77826d22b)
![1~AG7EWS_}E{_N0RTEXXCYE](https://github.com/BlinkDL/RWKV-LM/assets/96619920/a0feeea2-e0dc-4774-8999-066af399e730)
自己的参数设置如图：
![_R~}$7SI1$)GTY9)(2VPWS](https://github.com/BlinkDL/RWKV-LM/assets/96619920/491ce0ee-364d-42b6-8177-1cd31c5f0fc0)
头秃哇。。。

**Comment by BlinkDL** [comment]
可能是内存不足

**Comment by surviveMiao** [comment]
对的对的，是内存不足的原因。 没想到微调7b模型 128的内存都不够用。

**Comment by surviveMiao** [comment]
> 可能是内存不足

感谢您的回复，谢谢
