### ISSUE TITLE
Radeon Open Compute support

### ISSUE THREAD

**Issue by erkinalp** [BlinkDL/RWKV-LM#22]
There are many users with AMD graphics cards that want to train this model in a GPU accelerated manner. Radeon Open Compute is AMD's equivalent to CUDA (the relevant component in Radeon Open Compute is called HIP).

- [ ] Attempt to HIPify the codebase
- [ ] Make the HIP port optimised for full performance

**Comment by BlinkDL** [comment]
Cool. Let me know if you will work on it

**Comment by BlinkDL** [comment]
Here is AMD Ubuntu 22.04 GPU guide
https://github.com/BlinkDL/ChatRWKV/issues/15

**Comment by linwk20** [comment]
Cool, waiting for it.

**Comment by erkinalp** [comment]
subtask 2 is not complete, should be reopened
