### ISSUE TITLE
RWKV for Text to Speech use case

### ISSUE THREAD

**Issue by rishikksh20** [BlinkDL/RWKV-LM#222]
Hi @BlinkDL 
Have you ever experimented how RWKV is performing for speech use cases like text to speech ?

**Comment by BlinkDL** [comment]
a community member tried this. join our discord https://discord.gg/bDSBUMeFpc and check https://discord.com/channels/992359628979568762/1016606571993763861/1180965095589806080

**Comment by rishikksh20** [comment]
thanks @BlinkDL
