### ISSUE TITLE
Access/train to use the embeddings

### ISSUE THREAD

**Issue by jn2clark** [BlinkDL/RWKV-LM#24]
Hi @BlinkDL ! Really interested in your work here. I am looking to test out some of the models for embedding based tasks. What is the best way to access the embeddings? I would be looking to use these for training as well (i.e. contrastive loss using siamese training setup). Any information on this would be greatly appreciated.

**Comment by BlinkDL** [comment]
Thanks :)  from the README here:
Read the inference code in src/model.py and try using the final hidden state（.xx .aa .bb) as a faithful sentence embedding for other tasks. Probably you shall begin with .xx and .aa/.bb (.aa divided by .bb).

**Comment by tiendung** [comment]
Can you explaim future? still don't get what they mean and which value should be use. xx or aa / bb?

**Comment by BlinkDL** [comment]
@tiendung the hidden state has 5 tensors per block (att+ffn): xx aa bb pp xx

**Comment by KnutJaegersberg** [comment]
I'm now doing this in HF transformers. 430m seems faithful on writing style, not content.

**Comment by KnutJaegersberg** [comment]
There is a function in gptcache that does this, too. I'm using that code in my HF transformers code, it's just a few lines. 

https://gptcache.readthedocs.io/en/latest/_modules/gptcache/embedding/rwkv.html?highlight=rwkv#
