### ISSUE TITLE
RWKV支持对prefill过程中的统一前缀进行cache的操作吗

### ISSUE THREAD

**Issue by Lier007** [BlinkDL/RWKV-LM#270]
输入1：长doc+短q1
输入2：长doc+短q2
输入3：长doc+短q3
.....

我的场景如上所示：其中长doc都是一致的，后续的短q不一致，且每次的输出都很短，主要计算量都在长doc的prefill上，

想请教下RWKV的推理框架支持将长doc的prefill进行提前cache吗？

**Comment by BlinkDL** [comment]
因为RWKV是RNN，所以做这个尤其方便
先计算长doc，得到state s0
然后 s0 + q1 => s1
然后 s0 + q2 => s2
...
你可以看 https://pypi.org/project/rwkv/ 的例子

**Comment by Lier007** [comment]
嗯嗯是的  明白了  大佬牛批
就推理而论 RWKV和长文档是真滴搭
