### ISSUE TITLE
Question about the training compute

### ISSUE THREAD

**Issue by ogencoglu** [BlinkDL/RWKV-LM#32]
Great work! I am working on a survey and would be interested to know the total training compute (FLOPs) of RWKV-14B model? What was the training time (GPU-hours) on how many A100s? Also any idea about the GPU utilization rate?

**Comment by BlinkDL** [comment]
RWKV 14B: 3 months for 332G tokens on 8x8=64 A100-40Gs. Note I was using very small bsz (8x8x2=128, seems good for slightly better model performance) and it could be 50% faster if you use larger bsz.
