### ISSUE TITLE
Which model could be trained with one single RTX-4090(24G vram)?

### ISSUE THREAD

**Issue by changtimwu** [BlinkDL/RWKV-LM#34]
I apologize for asking such a simple question. I am planning to buy a GPU to evaluate RWKV, and I would like to get an RTX-4090. Does anyone know which model would allow me to make full use of a single 4090 while training?

**Comment by BlinkDL** [comment]
Try Deepspeed with offload :)

Or finetuning with LORA: https://github.com/Blealtan/RWKV-LM-LoRA
