### ISSUE TITLE
Repeated download errors - wrong readme?

### ISSUE THREAD

**Issue by Manamama** [BlinkDL/RWKV-LM#35]
Re: 
`Download RWKV-4 0.1/0.4/1.5/3/7/14B weights: https://huggingface.co/BlinkDL`
But how? 
I have repeated errors 
```
OSError: BlinkDL/rwkv-4-pile-430m does not appear to have a file named config.json. Checkout 'https://huggingface.co/BlinkDL/rwkv-4-pile-430m/main' for available files.
@6Y3GRwDjtGVo4nAe2 ➜ ~/Downloads/ChatRWKV (main) $ 

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/BlinkDL/rwkv-4-pile-430m/resolve/main/config.json
```

whatever model I try via simple:
```
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("BlinkDL/rwkv-4-pile-430m" , use_auth=True)
model = AutoModelForCausalLM.from_pretrained("BlinkDL/rwkv-4-pile-430m", use_auth=True)
```

Even AI gives up:

> Here are the steps for creating your own config.json file based on the model specifications and loading it locally:
> 
> First, you need to know the model architecture and hyperparameters of the model you want to download. You can try to find this information from the model page or contact the author for details.
> Second, you need to create a PretrainedConfig object that matches the model specifications. You can use one of the subclasses of PretrainedConfig from HuggingFace’s library depending on the model type[1](https://huggingface.co/transformers/v4.8.0/main_classes/configuration.html).
> Third, you need to save your PretrainedConfig object as a config.json file using to_json_file method[2](https://discuss.huggingface.co/t/how-to-create-a-config-json-after-saving-a-model/10459). You can specify a local path where you want to save this file.
> Fourth, you need to load the model using from_pretrained with local_files_only=True and provide the path to your config.json file[3](https://stackoverflow.com/questions/64550503/huggingface-saving-tokenizer). You also need to provide the path to other model files such as pytorch_model.bin.
etc.

This 
```
import os
from copy import deepcopy
from rwkv.model import RWKV

os.environ["RWKV_JIT_ON"] = '1'
os.environ["RWKV_CUDA_ON"] = '0' # if '1' then use CUDA kernel for seq mode (much faster)
from rwkv.model import RWKV                         # everything in /v2/rwkv folder
model = RWKV(model='/fsx/BlinkDL/HF-MODEL/rwkv-4-pile-1b5/RWKV-4-Pile-1B5-20220903-8040', strategy='cuda fp16')

out, state = model.forward([187, 510, 1563, 310, 247], None)   # use 20B_tokenizer.json
print(out.detach().cpu().numpy())                   # get logits
out, state = model.forward([187, 510], None)
out, state = model.forward([1563], state)           # RNN has state (use deepcopy if you want to clone it)
out, state = model.forward([310, 247], state)
print(out.detach().cpu().numpy())                   # same result as above

```

does not work either:
@6Y3GRwDjtGVo4nAe2 ➜ ~/Downloads/ChatRWKV (main) $ pip install rwkv
ERROR: Could not find a version that satisfies the requirement rwkv (from versions: none)
ERROR: No matching distribution found for rwkv
@6Y3GRwDjtGVo4nAe2 ➜ ~/Downloads/ChatRWKV (main) $ pip install rwkv-rs
Collecting rwkv-rs
  Downloading rwkv_rs-0.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 6.6 MB/s eta 0:00:00
Installing collected packages: rwkv-rs
Successfully installed rwkv-rs-0.2.3
@6Y3GRwDjtGVo4nAe2 ➜ ~/Downloads/ChatRWKV (main) $ python transf.py 
Traceback (most recent call last):
  File "/home/codespace/Downloads/ChatRWKV/transf.py", line 3, in <module>
    from rwkv.model import RWKV
ModuleNotFoundError: No module named 'rwkv'

etc.

**Comment by Manamama** [comment]
Update: OK, this works:
`pip install rwkvstic`

thus:                                                                  
```
import subprocess

# Install the package
subprocess.call(['pip', 'install', 'rwkvstic'])

import os
from copy import deepcopy
from rwkvstic.load import RWKV

os.environ["RWKV_JIT_ON"] = '1'
os.environ["RWKV_CUDA_ON"] = '0' # if '1' then use CUDA kernel for seq mode (much faster)
#from rwkv.model import RWKV                         # everything in /v2/rwkv folder
#model = RWKV(model='/fsx/BlinkDL/HF-MODEL/rwkv-4-pile-1b5/RWKV-4-Pile-1B5-20220903-8040', strategy='cuda fp16')
from rwkvstic.load import RWKV
model = RWKV("https://huggingface.co/BlinkDL/rwkv-4-pile-3b/resolve/main/RWKV-4-Pile-3B-Instruct-test1-20230124.pth")
#model = RWKV("https://huggingface.co/BlinkDL/rwkv-4-pile-430m/blob/main/RWKV-4b-Pile-436M-20230211-8012.pth")
#model = RWKV("https://huggingface.co/BlinkDL/rwkv-4-pile-430m/blob/main/RWKV-4-Pile-430M-20220808-8066.pth")
model = RWKV("https://huggingface.co/BlinkDL/rwkv-4-pile-169m/blob/main/RWKV-4-Pile-169M-20220807-8023.pth")
```

etc.

**Comment by BlinkDL** [comment]
Or you can manually download the weights such as:
https://huggingface.co/BlinkDL/rwkv-4-pile-7b/tree/main

**Comment by BlinkDL** [comment]
rwkv is not a pip package yet. It means this folder: https://github.com/BlinkDL/ChatRWKV/tree/main/v2/rwkv
