### ISSUE TITLE
Why isn't everyone using RWKV if it's so much better than transformers?

### ISSUE THREAD

**Issue by mrconter1** [BlinkDL/RWKV-LM#39]
Hi!

The machine learning (ML) community is progressing at a remarkable pace and is embracing new techniques very quickly. Based on my comprehension of this model, it appears to offer a distinct set of advantages relative to transformers, while lacking any real drawbacks. Despite these benefits, it remains unclear why adopting this approach is not more widespread among individuals and organizations in the field. 

Why is this the case? I really can't wrap my head around it.

**Comment by BlinkDL** [comment]
Because this is mostly a single-dev project :) Give it some time.
