### ISSUE TITLE
Implementation details about wkv

### ISSUE THREAD

**Issue by kxzxvbk** [BlinkDL/RWKV-LM#40]
Amazing work!
But I'm really confused about the implementation details for wkv cuda kernel (in RWKV-LM\RWKV-v4neo\cuda\wkv_cuda.cu).
How does the implementation match the equations shown in README? Could you please give a more detailed comment about it?
For example, what is the meaning of local variable p, pp, ...
Thanks

**Comment by BlinkDL** [comment]
compare with the code here :)
https://github.com/BlinkDL/ChatRWKV/blob/main/src/model_run.py
