### ISSUE TITLE
Context limits.

### ISSUE THREAD

**Issue by Ph0rk0z** [BlinkDL/RWKV-LM#42]
So I edited ooba to support 4096 contexts and this used to work in the past. 

In your module I see context also limited by the cuda kernel in either an env or a hardcoded ~1024. Am I understanding that part right? Will I have to compile my own rwkv.py?

https://github.com/Ph0rk0z/text-generation-webui/commits/RWKV-4096-Context

**Comment by BlinkDL** [comment]
It supports 8192 as of now. Can be modified to support "infinite" ctxlen (and reduce VRAM usage too) with a better implementation (simple, but too busy to do it right now lol).

**Comment by Ph0rk0z** [comment]
I am blocked by cuda version so can't test it yet. Plus I have to rewrite it now with UI changes.

**Comment by BlinkDL** [comment]
CUDA works for old GPUs now :)
