### ISSUE TITLE
ChatRWKV triggers segmentation fault when using streaming or split loading on 4-14B

### ISSUE THREAD

**Issue by nanonomad** [BlinkDL/RWKV-LM#44]
Hi,
This is probably something related to my setup, but I can't work out what's causing this.  When attempting to load the v4 14B model with ChatRWKV v2 with the split or stream methods, I get a segmentation fault midway through loading.  With cuda fp16i8 *1+ or  fp16 *1+, it simply segmentation faults sooner than cuda fp16 *10+ or cuda fp16i8 *10+.  Fp32 with split and stream behaves the same way.

I've tried loading the model with fp16i8 all to the GPU to see if it would do the same thing, but with cuda fp16i8 it will load up until it runs out of memory.

Any advice would be appreciated.

Ubuntu 20.04 on WL2
python 3.10
torch 1.13.1 cu117
pip rwkv 0.5
and always latest git pull

7B model works great because I can load it all on a 12gb GPU.

Really impressive project, and that's a total understatement.  I'm blown away by the 7b model.

**Comment by BlinkDL** [comment]
Currently it requires huge amt (probably 40G+?) of CPU RAM to load 14B. See https://github.com/BlinkDL/ChatRWKV/issues/41

Will be fixed soon :)

**Comment by nanonomad** [comment]
Thank you.  Sorry for troubling you with the post - searched but didn't come up with the linked reply.  I think you're going to be getting this one a lot, because this is not onaly a great project, but its accessible on retail hardware.

Looking forward to any optimizations that could make this work on 32gb. I think my 2-slot board is maxed out, and it took a heatgun and a rubber mallet to get a 3080 into this HP Omen prebuilt, so the thing is never coming apart again lol

And thank you for all the work you've put in to this project.

**Comment by BlinkDL** [comment]
This will be fixed in https://github.com/BlinkDL/ChatRWKV/issues/40 very soon :)

**Comment by BlinkDL** [comment]
Update ChatRWKV v2 & pip rwkv package (0.7.0):
Use v2/convert_model.py to convert a model for a strategy, for faster loading & saves CPU RAM.
@nanonomad
