### ISSUE TITLE
Question about RWKV-v2-RNN

### ISSUE THREAD

**Issue by AlanYeg** [BlinkDL/RWKV-LM#47]
I found that RWKV-v2-RNN has the same architecture as other version of RWKV,So Why call it RWKV-v2-RNN instead of RWKV-v2?
Am i missing some thing about   RWKV-v2-RNN's code?

**Comment by BlinkDL** [comment]
v1 is not an RNN
v2 is an RNN
then I remove the "RNN" part from name to keep it short :)
