### ISSUE TITLE
fine tuning a pretrained model with txt file

### ISSUE THREAD

**Issue by revive** [BlinkDL/RWKV-LM#49]
I tried to fine tuning a 3B model with a text file, encoded in UTF8, using the provided `train.py`.

It seems that the tokens are calculated with the unique characters. So I got
``` 
Building token list...                                                                                        
Data has 330926472 tokens, 7129 vocab size.
```
and error message
```
RuntimeError: Error(s) in loading state_dict for RWKV:                                                        
        size mismatch for emb.weight: copying a param with shape torch.Size([50277, 2560]) from checkpoint,   
the shape in current model is torch.Size([7129, 2560]).                                                       
        size mismatch for head.weight: copying a param with shape torch.Size([50277, 2560]) from checkpoint,  
the shape in current model is torch.Size([7129, 2560]).
```

I think I need to tokenize the text file with the same tokenizer to prepare the pile data before I fed it to the training script. Is there an example?

**Comment by BlinkDL** [comment]
Fine-tuning RWKV-4 Pile models: use 'prepare-data.py' in https://github.com/BlinkDL/RWKV-v2-RNN-Pile/tree/main/RWKV-v3 to tokenize .txt into train.npy data. Then set EXPRESS_PILE_MODE to True in v4/train.py, and run it.

Read the inference code in src/model.py and try using the final hidden state（.xx .aa .bb) as a faithful sentence embedding for other tasks. Probably you should begin with .xx and .aa/.bb (.aa divided by .bb).

Colab for fine-tuning RWKV-4 Pile models: https://colab.research.google.com/github/resloved/RWKV-notebooks/blob/master/RWKV_v4_RNN_Pile_Fine_Tuning.ipynb
