### ISSUE TITLE
The universe is like an RNN too (because of locality)

### ISSUE THREAD

**Issue by felri** [BlinkDL/RWKV-LM#50]
> I believe RNN is a better candidate for fundamental models, because: (1) It's more friendly for ASICs (no kv cache). (2) It's more friendly for RL. (3) When we write, our brain is more similar to RNN. (4) The universe is like an RNN too (because of locality). Transformers are non-local models.

I don't want to be _that_ guy, but [The Universe Is Not Locally Real, and the Physics Nobel Prize Winners Proved It](https://www.scientificamerican.com/article/the-universe-is-not-locally-real-and-the-physics-nobel-prize-winners-proved-it/)

**Comment by BlinkDL** [comment]
Locality is one of the principles behind QFT :)

See https://physics.stackexchange.com/questions/367378/locality-in-qft-vs-non-local-in-qm
