### ISSUE TITLE
The experimental results on the homepage are based on zero-shot learning？

### ISSUE THREAD

**Issue by AIRedWood** [BlinkDL/RWKV-LM#52]
Dear author

 I was wondering if I could ask you a question about your experiment results. Specifically, I'm curious to know if your results were based on zero-shot, one-shot, or few-shot conditions.。 [experiment results lnk](https://github.com/BlinkDL/RWKV-LM/raw/main/RWKV-eval.png)

**Comment by BlinkDL** [comment]
These are all zero-shot scores, and they are all trained on the Pile, so directly comparable
