### ISSUE TITLE
Any results on few-shot settings?

### ISSUE THREAD

**Issue by ustcwhy** [BlinkDL/RWKV-LM#53]
Thanks for your wonderful work!
Do you have any results on the few-shot settings? Do RWKV-LLMs perform the similar emergent ability like GPT-3, e.g. the chain-of-thought?

**Comment by BlinkDL** [comment]
RWKV is quite good at few-shot.
You can try it on https://huggingface.co/spaces/BlinkDL/ChatRWKV-gradio

Note chain-of-thought usually requires larger models (maybe ~30B) or a finetuned model (I can do this when there is a CoT dataset).
