### ISSUE TITLE
Training speed check

### ISSUE THREAD

**Issue by aljungberg** [BlinkDL/RWKV-LM#63]
Just curious about this number:

> Training speed: (new training code) RWKV-4 14B BF16 ctxlen4096 = 114K tokens/s on 8x8 A100 80G 

So to clarify, you're ingesting 114 ktokens/s on 64x A100s during training, or ~1.7k/s/GPU?

For comparison, Meta trained Llama 13B on 1T tokens in 135,168 GPU hours (also A100-80GB), which is ~0.0074B tokens/GPU/hour. You're achieving 0.0064B tokens/GPU/hour if my quick math is right, so training performance is quite comparable with Meta's even that they make a point of saying how heavily they optimised their training. (They say they hand-coded their backward functions and did work to parallelise activation computatiopn with GPU communication, although AFAIK they [didn't release their training code](https://github.com/facebookresearch/llama/issues/6)). That's impressive!

And that's on 4k context size? Traditional transformer dot product attention is `O(n^2)` on sequence length so going from 2k to 4k should 4x the compute, so I guess Llama would have only achieved 0.00185B tokens/GPU/hour with the same window size used here.

**Comment by BlinkDL** [comment]
1. Yes RWKV trains faster than GPT. I think there is at least still room for 30% optimization.
2. RWKV training speed (token/s) is actually independent of ctxlen.

**Comment by aljungberg** [comment]
That's awesome, thanks for clarifying!
