### ISSUE TITLE
Pretrained model license in README

### ISSUE THREAD

**Issue by kno10** [BlinkDL/RWKV-LM#76]
The README says the models will be open-source, which I appreciate a lot.
The huggingface model repositories are tagged as Apache license.
May I suggest to also mention the Apache license explicitly in the README.md (on huggingface) so there is no doubt?
Thank you - IMHO in particular Raven has great potential given the licensing issues of LLaMA.

**Comment by BlinkDL** [comment]
HF has license (Apache v2) if you look carefully :)

**Comment by kno10** [comment]
Yes, as I wrote above. But the hf metadata is subtle, and hence I suggest to nevertheless add it to the README itself.
