### ISSUE TITLE
Renaming for better visibility

### ISSUE THREAD

**Issue by whyplum** [BlinkDL/RWKV-LM#77]
Thank you for true open source alternative to all llamas. 
I have been running the framework trying to keep the original name: "rwkv" and I found it hard to type without misspellings 😅 
Have you considered renaming the repo to something easier to pronounce (and remember)?
Here is my proposal:

Ryuk-LM

if you watched Death Note of course ;)

**Comment by BlinkDL** [comment]
Or you can remember it as "Read Write Key Value" :)
