### ISSUE TITLE
RWKV4's trainer.py uses LightningLite which no longer exists

### ISSUE THREAD

**Issue by Maykeye** [BlinkDL/RWKV-LM#80]
If I run colab from README:

https://colab.research.google.com/github/resloved/RWKV-notebooks/blob/master/RWKV_v4_RNN_Pile_Fine_Tuning.ipynb

It will install lightning of the latest version, "Downloading pytorch_lightning-2.0.1.post0-py3-none-any.whl" as of right now.

And when the notebook runs train.py, it crashes

```console
023-04-12 02:19:38 - INFO - torch.distributed.nn.jit.instantiator - Writing /tmp/tmpmx8bmx82/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/content/RWKV-LM/RWKV-v4/train.py", line 191, in <module>
    from src.trainer import Trainer, TrainerConfig
  File "/content/RWKV-LM/RWKV-v4/src/trainer.py", line 15, in <module>
    from pytorch_lightning.lite import LightningLite
ModuleNotFoundError: No module named 'pytorch_lightning.lite'
```

Reading Lightning changelog, it seems now the code should rely on  `from lightning_fabric.fabric import Fabric` instead of `from pytorch_lightning.lite import LightningLite`: as since [2.0.0](https://github.com/Lightning-AI/lightning/releases/tag/2.0.0#bc-changes-fabric) "LightningLite is dead, long live Lightning Fabric!"

**Comment by BlinkDL** [comment]
Use pytorch_lightning 1.9.1

**Comment by Maykeye** [comment]
Then fix it in the training book. It explicitly says to use the latest version

> !pip install transformers pytorch-lightning deepspeed wandb ninja
