### ISSUE TITLE
Plug-in system?

### ISSUE THREAD

**Issue by josergc** [BlinkDL/RWKV-LM#82]
Hi team! Thank you for your hard work!

I was browsing the code and I was wondering if the system supports plug-ins or, if it does not have this kind of support, if there is any plan in regards, or if it could be enhanced with a plug-in system, like doing a search in google, a calendar, read a CSV file, perform any request to an API because a petition, etc. How could the system be enhanced or where to put this kind of systems?

Best regards,

**Comment by BlinkDL** [comment]
Hi I think you can use rwkv for https://github.com/hwchase17/langchain although i am not sure whether their implementation is buggy

**Comment by josergc** [comment]
thanks @BlinkDL ! I will explore this way to understand the way to extend the project in features
