### ISSUE TITLE
Max context length possible for 14B model 

### ISSUE THREAD

**Issue by HarshaKodali1** [BlinkDL/RWKV-LM#83]
Hi,

Max context length possible for 14B model , how to achieve that. 

I have a 3090 workstation. Want to build Autogpt with 14B model. 32K context possible?

**Comment by BlinkDL** [comment]
Yeah 32K context possible when I am less busy.

**Comment by ekg** [comment]
@BlinkDL with more RAM is 32k possible?

What are the changes you'll need to make to scale the context length more efficiently?

**Comment by BlinkDL** [comment]
Don't need more VRAM. Split input into 8K chunks and "pass" the gradient within chunks.
