### ISSUE TITLE
Add `Model-based Deep Reinforcement Learning` to RWKV-LM?

### ISSUE THREAD

**Issue by linkerlin** [BlinkDL/RWKV-LM#85]
What about add some `Model-based Deep Reinforcement Learning` to RWKV-LM?

**Comment by linkerlin** [comment]
![image](https://user-images.githubusercontent.com/37062/232235894-c405f1df-f8c1-4c51-ad78-54870e56b4da.png)

**Comment by BlinkDL** [comment]
We need to build a world model first ;)
https://github.com/BlinkDL/WorldModel
