### ISSUE TITLE
Please advise on understanding this output

### ISSUE THREAD

**Issue by webpolis** [BlinkDL/RWKV-LM#86]
![image](https://user-images.githubusercontent.com/1072797/232238748-80b8a486-6fde-4528-a8c2-c45000d24b3c.png)

I wish to understand how can the response be improved. I tried many different parameters, but the model fails to make the proper relationship connections between the characters.

**Comment by BlinkDL** [comment]
Instruction = your question
Input = useful materials
SET TOP_P = 0 !!!

**Comment by webpolis** [comment]
Thanks! Yeah, I later found the comments in the code about setting temp + top_p low for higher accuracy.


It's odd that I understood **instruction** would hold the task assignment's material or context while **input** holds for the question, and not the reverse.
