### ISSUE TITLE
Implement GPTQ for RWKV

### ISSUE THREAD

**Issue by 3outeille** [BlinkDL/RWKV-LM#88]
@BlinkDL Hi, I am willing to dedicate some time to implement GPTQ for RWKV, is that okay ?

**Comment by BlinkDL** [comment]
This is exactly what we need :) Please work on ChatRWKV

And please take a look at https://github.com/hahnyuan/RPTQ4LLM

**Comment by 3outeille** [comment]
Referencing https://github.com/BlinkDL/ChatRWKV/pull/98 for any questions related to this topic
