### ISSUE TITLE
如何给RWKV添加其他的神经网络

### ISSUE THREAD

**Issue by dataangel** [BlinkDL/RWKV-LM#93]
比如给他加一个GCN网络

**Comment by BlinkDL** [comment]
可以将RWKV看成一个模块，替换原有网络的MHA模块。

**Comment by FogSue** [comment]
> 可以将RWKV看成一个模块，替换原有网络的MHA模块。

意思是可以只用time-mixing替换mha，不引入channel-mixing吗
